include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_shadowing_type_parameters: false
    await_only_futures: true
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    file_names: false
    constant_identifier_names: false
    no_leading_underscores_for_local_identifiers: false
